up:
  - python: 3.6.6
  - pip:
    - requirements-dev.txt
  - python_develop

commands:
  test:
    run: nosetests

  release:
    run: pyreleaser create --only-on master --push
  publish:
    run: pyreleaser upload
